# Generated by Django 4.0.3 on 2023-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_detail_pics')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('location', models.CharField(max_length=100)),
                ('milage', models.IntegerField(default=0)),
                ('engine_type', models.CharField(max_length=30)),
                ('interior_color', models.CharField(choices=[('Yellow', 'Yellow'), ('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Red', 'Red'), ('Dark Blue', 'Dark Blue'), ('Light Blue', 'Light Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Beige', 'Beige')], default='Black', max_length=30)),
                ('exterior_color', models.CharField(choices=[('Yellow', 'Yellow'), ('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Red', 'Red'), ('Dark Blue', 'Dark Blue'), ('Light Blue', 'Light Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Beige', 'Beige')], default='Black', max_length=30)),
                ('vin', models.CharField(max_length=100)),
                ('car_id', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='cars_initial_pics')),
                ('transmission', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Automatic', 'Automatic'), ('Robotized', 'Robotized'), ('Variator', 'Variator')], default='Automatic', max_length=30)),
                ('fog_light', models.BooleanField(default=False)),
                ('push_start', models.BooleanField(default=False)),
                ('reverse_camera', models.BooleanField(default=False)),
                ('sun_roof', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
