# Generated by Django 4.0.3 on 2023-11-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purpose',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Pay And Drive', 'For Pay And Drive')], default='For Sale', max_length=50),
        ),
    ]
