# Generated by Django 4.0.3 on 2023-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0005_vehicle_rent_type_alter_vehicle_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(choices=[('Self Drive', 'Self Drive'), ('With Driver', 'With Driver')], default='Pay And Drive', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rent_type',
            field=models.CharField(choices=[('Pay And Drive', 'Pay And Drive'), ('Drive And Pay', 'Drive And Pay')], default='With Driver', max_length=50),
        ),
    ]
