# Generated by Django 4.0.3 on 2024-03-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0008_alter_vehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='rent_type',
            field=models.CharField(choices=[('Pay And Drive', 'Pay And Drive'), ('Drive And Pay', 'Drive And Pay'), ('Buy', 'Buy')], default='Pay And Drive', max_length=50),
        ),
    ]
