# Generated by Django 4.0.3 on 2023-11-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default_user.png', upload_to='profile_pics')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
