# Generated by Django 4.0.3 on 2023-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_approved',
            field=models.BooleanField(default=False),
        ),
    ]
