# Generated by Django 4.0.3 on 2023-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_approved',
            field=models.CharField(blank=True, default='Not approved', max_length=16),
        ),
    ]
