# Generated by Django 4.0.3 on 2023-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_approved',
            field=models.CharField(choices=[('Not Approved', 'Not Approved'), ('Approved', 'Approved')], default='Not Approved', max_length=16),
        ),
    ]
