# Generated by Django 4.0.3 on 2023-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_addtobooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtobooked',
            name='flight_booked',
            field=models.CharField(default='Booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='airline',
            field=models.CharField(choices=[('Africa World Airlines', 'Africa World Airlines'), ('PassionAir', 'PassionAir')], default='PassionAir', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arrival_airport',
            field=models.CharField(choices=[('Kumasi Airport (KMS)', 'Kumasi Airport (KMS)'), ('Accra Airport(ACC)', 'Accra Airport(ACC)')], default='Kumasi Airport (KSI)', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_airport',
            field=models.CharField(choices=[('Kumasi Airport (KMS)', 'Kumasi Airport (KMS)'), ('Accra Airport(ACC)', 'Accra Airport(ACC)')], default='Kumasi Airport (KSI)', max_length=100),
        ),
    ]
