# Generated by Django 4.0.3 on 2023-11-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_addtobooked_flight_booked_alter_booking_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flight_booked',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked')], default='Pending', max_length=20),
        ),
    ]
