# Generated by Django 4.0.3 on 2023-11-18 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketing', '0005_alter_booking_flight_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(choices=[('Africa World Airlines', 'Africa World Airlines'), ('PassionAir', 'PassionAir')], default='PassionAir', max_length=100)),
                ('departure_airport', models.CharField(choices=[('Kumasi Airport (KMS)', 'Kumasi Airport (KMS)'), ('Accra Airport(ACC)', 'Accra Airport(ACC)'), ('Takoradi Airport(TKD)', 'Takoradi Airport(TKD)'), ('Tamale Airport(TML)', 'Tamale Airport(TML)'), ('Wa Airport(WZA)', 'Wa Airport(AWZA'), ('Sunyani Airport(NYI)', 'Sunyani Airport(NYI)')], default='Kumasi Airport (KSI)', max_length=100)),
                ('arrival_airport', models.CharField(choices=[('Kumasi Airport (KMS)', 'Kumasi Airport (KMS)'), ('Accra Airport(ACC)', 'Accra Airport(ACC)'), ('Takoradi Airport(TKD)', 'Takoradi Airport(TKD)'), ('Tamale Airport(TML)', 'Tamale Airport(TML)'), ('Wa Airport(WZA)', 'Wa Airport(AWZA'), ('Sunyani Airport(NYI)', 'Sunyani Airport(NYI)')], default='Kumasi Airport (KSI)', max_length=100)),
                ('flight_type', models.CharField(choices=[('Round Trip', 'Round Trip'), ('One Way', 'One Way')], default='Round Trip', max_length=100)),
                ('departure_date', models.CharField(max_length=20)),
                ('flight_duration', models.IntegerField(default=45)),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('returning_date', models.CharField(blank=True, max_length=20)),
                ('returning_time', models.CharField(blank=True, max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_booked', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked')], default='Pending', max_length=20)),
                ('adults', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=11)),
                ('infants', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=11)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_flight_to_request', to='ticketing.availableflights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flight_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='returning_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='returning_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=11),
        ),
        migrations.AddField(
            model_name='booking',
            name='infants',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=11),
        ),
        migrations.DeleteModel(
            name='AddToBooked',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_flight', to='ticketing.availableflights'),
        ),
    ]
