# Generated by Django 4.0.3 on 2023-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_availableflights_requestbooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbooking',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requestbooking',
            name='infants',
            field=models.IntegerField(default=0),
        ),
    ]
