# Generated by Django 4.0.3 on 2023-11-21 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_remove_availableflights_flight_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_phone_number',
            field=models.CharField(default='0244000000', max_length=15),
        ),
    ]
