# Generated by Django 4.0.3 on 2023-11-15 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive_pay', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdriveandpay',
            name='drive_type',
            field=models.CharField(choices=[('Self Drive', 'Self Drive'), ('With Driver', 'With Driver')], default='Self Drive', max_length=50),
        ),
        migrations.CreateModel(
            name='AddToApprovedDriveAndPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_being_approved_for_dnp', to=settings.AUTH_USER_MODEL)),
                ('drive_and_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive_pay.requestdriveandpay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_approved_for_dnp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
