# Generated by Django 4.0.3 on 2023-11-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_sales', '0003_vehicle_purpose'),
        ('drive_pay', '0003_requestdriveandpay_drive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdriveandpay',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_for_drive_and_pay', to='car_sales.vehicle'),
        ),
        migrations.AlterField(
            model_name='requestdriveandpay',
            name='period',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='requestdriveandpay',
            name='request_approved',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
