# Generated by Django 4.0.3 on 2023-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_pay', '0004_alter_requestdriveandpay_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtoapproveddriveandpay',
            name='user_tracker_sim',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
