# Generated by Django 4.0.3 on 2024-03-14 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drive_pay', '0008_paydailyforpayanddrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydailyforpayanddrive',
            name='month_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='paydailyforpayanddrive',
            name='year_paid',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
