# Generated by Django 4.0.3 on 2024-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_pay', '0010_alter_requestdriveandpay_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtoapproveddriveandpay',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
