# Generated by Django 4.0.3 on 2022-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidScheduleRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(blank=True, max_length=10)),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(blank=True)),
                ('reply', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmDriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_confirmed', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Not Confirmed', 'Not Confirmed')], default='Not Confirmed', max_length=50)),
                ('bank_payment_reference', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date_confirmed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, default='', max_length=100)),
                ('notification_tag', models.CharField(blank=True, default='', max_length=100)),
                ('notification_title', models.CharField(blank=True, max_length=200)),
                ('notification_message', models.TextField(blank=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=20)),
                ('notification_trigger', models.CharField(blank=True, choices=[('Triggered', 'Triggered'), ('Not Triggered', 'Not Triggered')], default='Triggered', max_length=100)),
                ('ride_id', models.CharField(blank=True, max_length=100)),
                ('ride_accepted_id', models.CharField(blank=True, max_length=100)),
                ('ride_rejected_id', models.CharField(blank=True, max_length=100)),
                ('completed_ride_id', models.CharField(blank=True, max_length=100)),
                ('schedule_ride_id', models.CharField(blank=True, max_length=100)),
                ('schedule_accepted_id', models.CharField(blank=True, max_length=100)),
                ('schedule_rejected_id', models.CharField(blank=True, max_length=100)),
                ('complain_id', models.CharField(blank=True, max_length=100)),
                ('reply_id', models.CharField(blank=True, max_length=100)),
                ('review_id', models.CharField(blank=True, max_length=100)),
                ('rating_id', models.CharField(blank=True, max_length=100)),
                ('payment_confirmed_id', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.CharField(blank=True, max_length=255)),
                ('drop_off', models.CharField(blank=True, max_length=255)),
                ('ride_accepted', models.BooleanField(default=False)),
                ('ride_rejected', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('driver_booked', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_pickup', models.DateField()),
                ('time_of_pickup', models.TimeField()),
                ('schedule_option', models.CharField(choices=[('One Time', 'One Time'), ('Daily', 'Daily'), ('Days', 'Days'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='One Time', max_length=30)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('confirmation_status', models.CharField(default='Not Accepted', max_length=20)),
                ('scheduled', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_scheduled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
