# Generated by Django 4.0.3 on 2022-08-20 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptAssignedScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateField(auto_now_add=True)),
                ('time_accepted', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AskToLoadWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Wants to load wallet', max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_requested', models.DateField(default=django.utils.timezone.now)),
                ('time_requested', models.TimeField(default=django.utils.timezone.now)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssignScheduleToDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_accepted', models.BooleanField(default=False)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('time_assigned', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelScheduledRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cancelled', models.DateField(auto_now_add=True)),
                ('time_cancelled', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedScheduledRidesToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmDriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('bank_payment_reference', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_confirmed', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DriversLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=100)),
                ('location_name', models.CharField(default='', max_length=100)),
                ('drivers_lat', models.CharField(blank=True, max_length=255, null=True)),
                ('drivers_lng', models.CharField(blank=True, max_length=255, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverVehicleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windscreen', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('side_mirror', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('registration_plate', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('tire_pressure', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('driving_mirror', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('tire_thread_depth', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('wheel_nuts', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('engine_oil', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('fuel_level', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('break_fluid', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('radiator_engine_coolant', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('power_steering_fluid', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('wiper_washer_fluid', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('seat_belts', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('steering_wheel', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('horn', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('electric_windows', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('windscreen_wipers', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('head_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('trafficators', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('tail_rear_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('reverse_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('interior_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('engine_noise', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('excessive_smoke', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('foot_break', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('hand_break', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('wheel_bearing_noise', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('warning_triangle', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('fire_extinguisher', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('first_aid_box', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('checked_today', models.BooleanField(default=False)),
                ('date_checked', models.DateField(auto_now_add=True)),
                ('time_checked', models.TimeField(auto_now_add=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PassengersWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_loaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectAssignedScheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejected', models.DateField(auto_now_add=True)),
                ('time_rejected', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, default='', max_length=100)),
                ('notification_tag', models.CharField(blank=True, default='', max_length=255)),
                ('notification_title', models.CharField(blank=True, max_length=255)),
                ('notification_message', models.TextField(blank=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=20)),
                ('notification_trigger', models.CharField(blank=True, choices=[('Triggered', 'Triggered'), ('Not Triggered', 'Not Triggered')], default='Triggered', max_length=255)),
                ('passengers_pickup', models.CharField(blank=True, max_length=255, null=True)),
                ('passengers_dropOff', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_ride_id', models.CharField(blank=True, max_length=255)),
                ('schedule_ride_accepted_id', models.CharField(blank=True, max_length=255)),
                ('schedule_ride_rejected_id', models.CharField(blank=True, max_length=255)),
                ('completed_schedule_ride_id', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('drivers_inventory_id', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_scheduled_id', models.CharField(blank=True, default='', max_length=255)),
                ('accept_assigned_scheduled_id', models.CharField(blank=True, default='', max_length=255)),
                ('reject_assigned_scheduled_id', models.CharField(blank=True, default='', max_length=255)),
                ('complain_id', models.CharField(blank=True, max_length=255)),
                ('reply_id', models.CharField(blank=True, max_length=255)),
                ('review_id', models.CharField(blank=True, max_length=255)),
                ('rating_id', models.CharField(blank=True, max_length=255)),
                ('payment_confirmed_id', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_title', models.CharField(default='', max_length=255)),
                ('schedule_type', models.CharField(choices=[('Select Schedule Type', 'Select Schedule Type'), ('One Time', 'One Time'), ('Daily', 'Daily'), ('Days', 'Days'), ('Weekly', 'Weekly'), ('Until Cancelled', 'Until Cancelled')], default='One Time', max_length=255)),
                ('schedule_priority', models.CharField(choices=[('Select Schedule Priority', 'Select Schedule Priority'), ('High', 'High'), ('Low', 'Low')], default='High', max_length=255)),
                ('schedule_description', models.TextField(default='')),
                ('ride_type', models.CharField(choices=[('Taxinet Ride', 'Taxinet Ride'), ('Taxinet Luxury', 'Taxinet Luxury')], default='Taxinet Ride', max_length=50)),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('drop_off_location', models.CharField(blank=True, max_length=255)),
                ('pick_up_time', models.CharField(blank=True, max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('date_scheduled', models.DateField(auto_now_add=True)),
                ('time_scheduled', models.TimeField(auto_now_add=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
            ],
        ),
    ]
