# Generated by Django 4.0.3 on 2022-11-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_users', '0001_initial'),
        ('taxinet_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workandpay',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallets',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_only_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='updatedwallets',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.wallets'),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='assigned_driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_to_be_assigned_schedule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_scheduling_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DeUser_receiving_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_to_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_receiving_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_to_passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger_receiving_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridemessages',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='ridemessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedscheduledrides',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rejecting_scheduled_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rejectedscheduledrides',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='rejectassignedscheduled',
            name='assigned_to_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.assignscheduletodriver'),
        ),
        migrations.AddField(
            model_name='rejectassignedscheduled',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passengerswallet',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_for_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passengerswallet',
            name='de_passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengerloadingwallet', to='taxinet_users.passengerprofile'),
        ),
        migrations.AddField(
            model_name='passengerswallet',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_only_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherwallet',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherwallet',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadwallet',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loadwallet_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loadwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesrequest',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_making_expense', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesrequest',
            name='guarantor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting_expense_cash', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivervehicleinventory',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivervehicleinventory',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverswallet',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_administrator_for_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverswallet',
            name='de_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverswallet', to='taxinet_users.driverprofile'),
        ),
        migrations.AddField(
            model_name='driverswallet',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_only_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverstarttrip',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start_trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverstarttrip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverstarttrip',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_enjoying_trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverslocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverendtrip',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_trip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverendtrip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverendtrip',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_enjoying_trip_to_end', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverasktoloadwallet',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_loadWallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverasktoloadwallet',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_users.driverprofile'),
        ),
        migrations.AddField(
            model_name='driveralertarrival',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveralertarrival',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_being_alerted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driveraddtoupdatedwallets',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.driverswallet'),
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmdriverpayment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completedscheduledrides',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='complains',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complains',
            name='complainant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_making_complain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complains',
            name='offender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelscheduledride',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_cancelling_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelscheduledride',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='assignscheduletodriver',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignscheduletodriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver_receiving_scheduled_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignscheduletodriver',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='asktoloadwallet',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asktoloadwallet',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_users.passengerprofile'),
        ),
        migrations.AddField(
            model_name='addtoupdatedwallets',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.passengerswallet'),
        ),
        migrations.AddField(
            model_name='addtopaymenttoday',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addtopaymenttoday',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptedscheduledrides',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_accepting_scheduled_ride', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptedscheduledrides',
            name='scheduled_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
        migrations.AddField(
            model_name='acceptassignedscheduled',
            name='assigned_to_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.assignscheduletodriver'),
        ),
        migrations.AddField(
            model_name='acceptassignedscheduled',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
