# Generated by Django 4.0.3 on 2022-08-22 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednotifications',
            name='notification_to_passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger_receiving_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
