# Generated by Django 4.0.3 on 2022-11-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleride',
            name='schedule_description',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='schedule_priority',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='schedule_title',
        ),
    ]
