# Generated by Django 4.0.3 on 2023-09-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCarForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('Select Card Type', 'Select Card Type'), ('Standard', 'Standard'), ('4WD/SUV', '4WD/SUV'), ('Van', 'Van')], default='Standard', max_length=100)),
                ('number_of_passengers', models.IntegerField(default=5)),
                ('transmission', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Automatic', 'Automatic'), ('Robotized', 'Robotized'), ('Variator', 'Variator')], default='Automatic', max_length=100)),
                ('air_condition', models.BooleanField(default=False)),
                ('car_color', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentACar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days_renting', models.IntegerField(default=1)),
                ('pick_up_time', models.CharField(max_length=30)),
                ('pick_up_date', models.CharField(max_length=30)),
                ('drop_off_time', models.CharField(max_length=30)),
                ('drop_off_date', models.CharField(max_length=30)),
                ('driver_type', models.CharField(choices=[('Select Driver Type', 'Select Driver Type'), ('Self Drive', 'Self Drive'), ('With A Driver', 'With A Driver')], default='Self Drive', max_length=255)),
                ('rent_status', models.CharField(choices=[('Booked', 'Booked'), ('Not Booked', 'Not Booked'), ('Completed', 'Completed')], default='Not Booked', max_length=105)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_renting', to=settings.AUTH_USER_MODEL)),
                ('rented_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_car', to='taxinet_api.registercarforrent')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('millage', models.CharField(default='', max_length=255)),
                ('windscreen', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('side_mirror', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('registration_plate', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('tire_pressure', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('driving_mirror', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('tire_thread_depth', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('wheel_nuts', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('engine_oil', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('fuel_level', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('break_fluid', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('radiator_engine_coolant', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('power_steering_fluid', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('wiper_washer_fluid', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('seat_belts', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('steering_wheel', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('horn', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('electric_windows', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('windscreen_wipers', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('head_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('trafficators', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('tail_rear_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('reverse_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('interior_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('engine_noise', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('excessive_smoke', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('foot_break', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('hand_break', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('wheel_bearing_noise', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('warning_triangle', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('fire_extinguisher', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('first_aid_box', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('checked_today', models.BooleanField(default=False)),
                ('date_checked', models.DateField(auto_now_add=True)),
                ('time_checked', models.TimeField(auto_now_add=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10)),
                ('inspector_name', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('administrator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='acceptassignedscheduled',
            name='assigned_to_driver',
        ),
        migrations.RemoveField(
            model_name='acceptassignedscheduled',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='acceptedscheduledrides',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='acceptedscheduledrides',
            name='scheduled_ride',
        ),
        migrations.RemoveField(
            model_name='addtoblocklist',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='addtoblocklist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='addtopaymenttoday',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='addtopaymenttoday',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='addtoupdatedwallets',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='asktoloadwallet',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='asktoloadwallet',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='assignscheduletodriver',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='assignscheduletodriver',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='assignscheduletodriver',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='callforinspection',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='completedscheduledrides',
            name='scheduled_ride',
        ),
        migrations.RemoveField(
            model_name='confirmdriverpayment',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driveraddtoupdatedwallets',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='driveralertarrival',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driveralertarrival',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='driverasktoloadwallet',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='driverasktoloadwallet',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverendtrip',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='driverendtrip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverendtrip',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='driverrequestcommission',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='driverrequestcommission',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='driverrequestcommission',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverscommission',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverslocation',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverstarttrip',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='driverstarttrip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverstarttrip',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='driverswallet',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='driverswallet',
            name='de_driver',
        ),
        migrations.RemoveField(
            model_name='driverswallet',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='drivertransfercommissiontowallet',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='drivervehicleinventory',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='drivervehicleinventory',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='expensesrequest',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='expensesrequest',
            name='guarantor',
        ),
        migrations.RemoveField(
            model_name='expensesrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='otherwallet',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='otherwallet',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='passengerswallet',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='passengerswallet',
            name='de_passenger',
        ),
        migrations.RemoveField(
            model_name='passengerswallet',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='paypromotercommission',
            name='promoter',
        ),
        migrations.DeleteModel(
            name='PrivateChatId',
        ),
        migrations.RemoveField(
            model_name='privateusermessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='privateusermessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='rejectassignedscheduled',
            name='assigned_to_driver',
        ),
        migrations.RemoveField(
            model_name='rejectassignedscheduled',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='rejectedscheduledrides',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='rejectedscheduledrides',
            name='scheduled_ride',
        ),
        migrations.RemoveField(
            model_name='ridemessages',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='ridemessages',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.RemoveField(
            model_name='userrequesttopup',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='userrequesttopup',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='userrequesttopup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='walletaddition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='walletdeduction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workandpay',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='workextra',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='workextra',
            name='driver',
        ),
        migrations.RenameField(
            model_name='schedulednotifications',
            old_name='schedule_ride_accepted_id',
            new_name='rent_car_id',
        ),
        migrations.RenameField(
            model_name='schedulednotifications',
            old_name='schedule_ride_rejected_id',
            new_name='rent_car_title',
        ),
        migrations.RemoveField(
            model_name='complains',
            name='offender',
        ),
        migrations.RemoveField(
            model_name='complains',
            name='read',
        ),
        migrations.RemoveField(
            model_name='schedulednotifications',
            name='accept_assigned_scheduled_id',
        ),
        migrations.RemoveField(
            model_name='schedulednotifications',
            name='assigned_scheduled_id',
        ),
        migrations.RemoveField(
            model_name='schedulednotifications',
            name='reject_assigned_scheduled_id',
        ),
        migrations.RemoveField(
            model_name='schedulednotifications',
            name='schedule_ride_slug',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='assigned_driver',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='days',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='driver_username',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='passenger_phone',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='passenger_username',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='read',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='ride_type',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='slug',
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day1',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day3',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day4',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day5',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day6',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='day7',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='schedule_duration',
            field=models.CharField(choices=[('Select Schedule Duration', 'Select Schedule Duration'), ('One Time', 'One Time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Days', 'Days')], default='One Time', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='schedule_type',
            field=models.CharField(choices=[('Select Schedule Type', 'Select Schedule Type'), ('School Pick up And Drop Off', 'School Pick up And Drop Off'), ('Office Pick up And Drop Off', 'Office Pick up And Drop Off'), ('Airport Pick up And Drop Off', 'Airport Pick up And Drop Off'), ('Delivery Pick up And Drop Off', 'Delivery Pick up And Drop Off'), ('Hotel Pick up And Drop Off', 'Hotel Pick up And Drop Off')], default='Airport Pick up And Drop Off', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='AcceptAssignedScheduled',
        ),
        migrations.DeleteModel(
            name='AcceptedScheduledRides',
        ),
        migrations.DeleteModel(
            name='AddToBlockList',
        ),
        migrations.DeleteModel(
            name='AddToPaymentToday',
        ),
        migrations.DeleteModel(
            name='AddToUpdatedWallets',
        ),
        migrations.DeleteModel(
            name='AskToLoadWallet',
        ),
        migrations.DeleteModel(
            name='AssignScheduleToDriver',
        ),
        migrations.DeleteModel(
            name='CallForInspection',
        ),
        migrations.DeleteModel(
            name='CompletedScheduledRides',
        ),
        migrations.DeleteModel(
            name='ConfirmDriverPayment',
        ),
        migrations.DeleteModel(
            name='DriverAddToUpdatedWallets',
        ),
        migrations.DeleteModel(
            name='DriverAlertArrival',
        ),
        migrations.DeleteModel(
            name='DriverAskToLoadWallet',
        ),
        migrations.DeleteModel(
            name='DriverEndTrip',
        ),
        migrations.DeleteModel(
            name='DriverRequestCommission',
        ),
        migrations.DeleteModel(
            name='DriversCommission',
        ),
        migrations.DeleteModel(
            name='DriversLocation',
        ),
        migrations.DeleteModel(
            name='DriverStartTrip',
        ),
        migrations.DeleteModel(
            name='DriversWallet',
        ),
        migrations.DeleteModel(
            name='DriverTransferCommissionToWallet',
        ),
        migrations.DeleteModel(
            name='DriverVehicleInventory',
        ),
        migrations.DeleteModel(
            name='ExpensesRequest',
        ),
        migrations.DeleteModel(
            name='MonthlySalary',
        ),
        migrations.DeleteModel(
            name='OtherWallet',
        ),
        migrations.DeleteModel(
            name='PassengersWallet',
        ),
        migrations.DeleteModel(
            name='PayPromoterCommission',
        ),
        migrations.DeleteModel(
            name='PrivateUserMessage',
        ),
        migrations.DeleteModel(
            name='RejectAssignedScheduled',
        ),
        migrations.DeleteModel(
            name='RejectedScheduledRides',
        ),
        migrations.DeleteModel(
            name='RideMessages',
        ),
        migrations.DeleteModel(
            name='UserRequestTopUp',
        ),
        migrations.DeleteModel(
            name='WalletAddition',
        ),
        migrations.DeleteModel(
            name='WalletDeduction',
        ),
        migrations.DeleteModel(
            name='WorkAndPay',
        ),
        migrations.DeleteModel(
            name='WorkExtra',
        ),
    ]
