# Generated by Django 4.0.3 on 2022-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_remove_scheduleride_confirmation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleride',
            name='date_of_pickup',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='drop_off_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='time_of_pickup',
            field=models.TimeField(blank=True),
        ),
    ]
