# Generated by Django 4.0.3 on 2022-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_alter_notifications_complain_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='drop_off_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='drop_off_lng',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestride',
            name='drop_off_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestride',
            name='drop_off_lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
