# Generated by Django 4.0.3 on 2023-09-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_registercarforrent_rentacar_vehicleinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercarforrent',
            name='picture',
            field=models.ImageField(default='taxinet_cab.png', upload_to='registered_cars'),
        ),
    ]
