# Generated by Django 4.0.3 on 2022-10-27 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_addtopaymenttoday_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignscheduletodriver',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride', unique=True),
        ),
    ]
