# Generated by Django 4.0.3 on 2022-08-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0003_schedulednotifications_notification_to_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asktoloadwallet',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asktoloadwallet',
            name='time_requested',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passengerswallet',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_only_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
