# Generated by Django 4.0.3 on 2022-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_scheduleride_ride_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleride',
            old_name='pick_up_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='ride_type',
            field=models.CharField(choices=[('Taxinet Ride', 'Taxinet Ride'), ('Taxinet Luxury', 'Taxinet Luxury')], default='Taxinet Ride', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='schedule_priority',
            field=models.CharField(choices=[('Select Schedule Priority', 'Select Schedule Priority'), ('High', 'High'), ('Low', 'Low')], default='High', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='schedule_type',
            field=models.CharField(choices=[('Select Schedule Type', 'Select Schedule Type'), ('One Time', 'One Time'), ('Daily', 'Daily'), ('Days', 'Days'), ('Weekly', 'Weekly'), ('Until Cancelled', 'Until Cancelled')], default='One Time', max_length=255),
        ),
    ]
