# Generated by Django 4.0.3 on 2022-11-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_remove_scheduleride_schedule_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleride',
            name='drop_off_lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='drop_off_lng',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='pickup_lat',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='pickup_lng',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
