# Generated by Django 4.0.3 on 2022-07-15 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0004_rename_pick_up_date_scheduleride_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleride',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='date_scheduled',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='time_scheduled',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
