# Generated by Django 4.0.3 on 2022-10-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0004_alter_assignscheduletodriver_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignscheduletodriver',
            name='ride',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride'),
        ),
    ]
