# Generated by Django 4.0.3 on 2022-04-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0004_alter_scheduleride_date_of_pickup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='reply',
        ),
    ]
