# Generated by Django 4.0.3 on 2022-06-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0004_driverannouncearrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='ride_distance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notifications',
            name='ride_duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='requestride',
            name='ride_distance',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='requestride',
            name='ride_duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
