# Generated by Django 4.0.3 on 2023-09-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0004_registercarforrent_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='register_car_images')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('registered_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.registercarforrent')),
            ],
        ),
    ]
