# Generated by Django 4.0.3 on 2022-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0004_notifications_drop_off_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searcheddestinations',
            name='drop_off_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searcheddestinations',
            name='drop_off_lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
