# Generated by Django 4.0.3 on 2022-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0004_driveralertarrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednotifications',
            name='schedule_ride_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
