# Generated by Django 4.0.3 on 2022-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0005_alter_assignscheduletodriver_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registervehicle',
            name='branded_wrap',
        ),
        migrations.RemoveField(
            model_name='registervehicle',
            name='fleet_car',
        ),
        migrations.RemoveField(
            model_name='registervehicle',
            name='light_box',
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='vehicle_brand',
            field=models.CharField(choices=[('Avalon', 'Avalon'), ('BELTA', 'BELTA'), ('CAMRY', 'CAMRY'), ('CENTURY', 'CENTURY'), ('ALLION', 'ALLION'), ('LEVIN GT', 'LEVIN GT'), ('CROWN', 'CROWN'), ('ETIOS', 'ETIOS'), ('MIRAI', 'MIRAI'), ('PRIUS', 'PRIUS'), ('AGYA', 'AGYA'), ('AQUA', 'AQUA'), ('COROLLA', 'COROLLA'), ('ETIOS', 'ETIOS'), ('GLANZA', 'GLANZA'), ('PASSO', 'PASSO'), ('YARIS', 'YARIS'), ('4RUNNER', '4RUNNER'), ('VENZA', 'VENZA'), ('HIGHLANDER', 'HIGHLANDER'), ('LAND CRUISER', 'LAND CRUISER'), ('RAV4', 'RAV4'), ('RUSH', 'RUSH'), ('Vitz', 'Vitz')], default='Vitz', max_length=255),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Inspection', 'Inspection'), ('In the shop', 'In the shop'), ('Stolen', 'Stolen'), ('In Garage', 'In Garage')], default='In Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='transmission',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Automatic', 'Automatic'), ('Robotized', 'Robotized'), ('Variator', 'Variator')], default='Automatic', max_length=30),
        ),
    ]
