# Generated by Django 4.0.3 on 2022-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0005_alter_scheduleride_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleride',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
