# Generated by Django 4.0.3 on 2022-11-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0005_privatechatid_expensesrequest_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='user',
        ),
    ]
