# Generated by Django 4.0.3 on 2022-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0005_remove_complains_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmdriverpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='confirmdriverpayment',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
