# Generated by Django 4.0.3 on 2022-06-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0005_notifications_ride_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='d_pick',
            field=models.CharField(default='', max_length=355),
        ),
        migrations.AddField(
            model_name='notifications',
            name='p_pick',
            field=models.CharField(default='', max_length=355),
        ),
        migrations.AddField(
            model_name='requestride',
            name='d_pick',
            field=models.CharField(default='', max_length=355),
        ),
        migrations.AddField(
            model_name='requestride',
            name='p_pick',
            field=models.CharField(default='', max_length=355),
        ),
    ]
