# Generated by Django 4.0.3 on 2023-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0005_registeredcarimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednotifications',
            name='notification_to_admin',
        ),
        migrations.RemoveField(
            model_name='schedulednotifications',
            name='notification_to_passenger',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='username',
        ),
        migrations.AlterField(
            model_name='wallets',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='LoadWallet',
        ),
    ]
