# Generated by Django 4.0.3 on 2022-06-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0006_notifications_d_pick_notifications_p_pick_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='d_pick',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='p_pick',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='d_pick',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='p_pick',
        ),
    ]
