# Generated by Django 4.0.3 on 2022-11-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0006_remove_stocks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleride',
            name='days',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
