# Generated by Django 4.0.3 on 2022-10-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0006_remove_registervehicle_branded_wrap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registervehicle',
            name='picture',
        ),
    ]
