# Generated by Django 4.0.3 on 2022-08-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_alter_addtoverified_user_addcardsuploaded'),
        ('taxinet_api', '0006_addtoupdatedwallets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerswallet',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_only_profile', to='taxinet_users.passengerprofile'),
        ),
    ]
