# Generated by Django 4.0.3 on 2022-04-11 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0006_alter_confirmdriverpayment_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateDriver',
            new_name='DriversPoints',
        ),
        migrations.RenameField(
            model_name='driverspoints',
            old_name='rating',
            new_name='points',
        ),
        migrations.AddField(
            model_name='confirmdriverpayment',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
