# Generated by Django 4.0.3 on 2022-10-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0007_remove_registervehicle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervehicle',
            name='year',
            field=models.CharField(default='2000', max_length=20),
        ),
    ]
