# Generated by Django 4.0.3 on 2022-08-26 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0007_alter_asktoloadwallet_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerswallet',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_only_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
