# Generated by Django 4.0.3 on 2022-08-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_alter_addtoverified_user_addcardsuploaded'),
        ('taxinet_api', '0007_alter_passengerswallet_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asktoloadwallet',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_users.passengerprofile'),
        ),
    ]
