# Generated by Django 4.0.3 on 2022-04-11 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0007_rename_ratedriver_driverspoints_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_lat', models.CharField(blank=True, max_length=100)),
                ('loc_lng', models.CharField(blank=True, max_length=100)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
