# Generated by Django 4.0.3 on 2022-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0007_remove_notifications_d_pick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedbidonride',
            name='passengers_lat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='completedbidonride',
            name='passengers_lng',
            field=models.CharField(default='', max_length=255),
        ),
    ]
