# Generated by Django 4.0.3 on 2022-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0008_assignscheduletodriver_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleride',
            name='active',
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Active', 'Active'), ('Not Active', 'Not Active')], default='Pending', max_length=50),
        ),
    ]
