# Generated by Django 4.0.3 on 2022-10-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0008_alter_registervehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallets',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wallets',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
