# Generated by Django 4.0.3 on 2022-04-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0008_driverslocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverslocation',
            old_name='loc_lat',
            new_name='lat_lng',
        ),
        migrations.RemoveField(
            model_name='driverslocation',
            name='loc_lng',
        ),
    ]
