# Generated by Django 4.0.3 on 2022-07-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0008_completedbidonride_passengers_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideStarted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.requestride')),
            ],
        ),
    ]
