# Generated by Django 4.0.3 on 2022-08-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0008_alter_passengerswallet_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleride',
            old_name='initial_payment',
            new_name='charge',
        ),
    ]
