# Generated by Django 4.0.3 on 2022-07-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0009_remove_scheduleride_active_scheduleride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleride',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Active', 'Active'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
