# Generated by Django 4.0.3 on 2022-07-06 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0009_ridestarted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleride',
            name='date_of_pickup',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='schedule_option',
        ),
        migrations.RemoveField(
            model_name='scheduleride',
            name='time_of_pickup',
        ),
        migrations.AddField(
            model_name='messages',
            name='time_sent',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='pick_up_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='pick_up_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='schedule_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='schedule_priority',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='High', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='schedule_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='schedule_type',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Daily', 'Daily'), ('Days', 'Days'), ('Weekly', 'Weekly'), ('Until Cancelled', 'Until Cancelled')], default='One Time', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='time_scheduled',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bidscheduleride',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ride_receiving_messages', to='taxinet_api.scheduleride'),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='date_scheduled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ScheduledNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, default='', max_length=100)),
                ('notification_tag', models.CharField(blank=True, default='', max_length=255)),
                ('notification_title', models.CharField(blank=True, max_length=255)),
                ('notification_message', models.TextField(blank=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=20)),
                ('notification_trigger', models.CharField(blank=True, choices=[('Triggered', 'Triggered'), ('Not Triggered', 'Not Triggered')], default='Triggered', max_length=255)),
                ('passengers_pickup', models.CharField(blank=True, max_length=255, null=True)),
                ('passengers_dropOff', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_ride_id', models.CharField(blank=True, max_length=255)),
                ('schedule_ride_accepted_id', models.CharField(blank=True, max_length=255)),
                ('schedule_ride_rejected_id', models.CharField(blank=True, max_length=255)),
                ('completed_schedule_ride_id', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('complain_id', models.CharField(blank=True, max_length=255)),
                ('reply_id', models.CharField(blank=True, max_length=255)),
                ('review_id', models.CharField(blank=True, max_length=255)),
                ('rating_id', models.CharField(blank=True, max_length=255)),
                ('payment_confirmed_id', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notification_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notification_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DeUser_receiving_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejected', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rejecting_scheduled_ride', to=settings.AUTH_USER_MODEL)),
                ('scheduled_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('scheduled_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedBidOnScheduledRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_completing_scheduled_ride', to=settings.AUTH_USER_MODEL)),
                ('scheduled_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_accepting_scheduled_ride', to=settings.AUTH_USER_MODEL)),
                ('scheduled_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride')),
            ],
        ),
    ]
