# Generated by Django 4.0.3 on 2022-08-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0009_rename_initial_payment_scheduleride_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverstarttrip',
            name='ride',
        ),
    ]
