# Generated by Django 4.0.3 on 2022-04-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0009_rename_loc_lat_driverslocation_lat_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverslocation',
            old_name='lat_lng',
            new_name='position_lat',
        ),
        migrations.AddField(
            model_name='driverslocation',
            name='position_lng',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
