# Generated by Django 4.0.3 on 2022-08-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0010_remove_driverstarttrip_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverendtrip',
            name='ride',
        ),
    ]
