# Generated by Django 4.0.3 on 2022-07-08 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0010_remove_scheduleride_date_of_pickup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windscreen', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('side_mirror', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('registration_plate', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('tire_pressure', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('driving_mirror', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('tire_thread_depth', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('wheel_nuts', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('engine_oil', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('fuel_level', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('break_fluid', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('radiator_engine_coolant', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('power_steering_fluid', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('wiper_washer_fluid', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('seat_belts', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('steering_wheel', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('horn', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('electric_windows', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('windscreen_wipers', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('head_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('trafficators', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('tail_rear_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('reverse_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('interior_lights', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('engine_noise', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('excessive_smoke', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('foot_break', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('hand_break', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('wheel_bearing_noise', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('warning_triangle', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('fire_extinguisher', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('first_aid_box', models.CharField(choices=[('Okay', 'Okay'), ('No', 'No')], default='No', max_length=10)),
                ('checked_today', models.BooleanField(default=False)),
                ('date_checked', models.DateField(auto_now_add=True)),
                ('time_checked', models.TimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='user',
        ),
        migrations.RemoveField(
            model_name='completedbidonride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='completedbidonride',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='completedrides',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='driverannouncearrival',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverannouncearrival',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='driverreviews',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverreviews',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='driverspoints',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driverspoints',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notification_from',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notification_to',
        ),
        migrations.RemoveField(
            model_name='rejectedrides',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='rejectedrides',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='ridestarted',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='searcheddestinations',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='sos',
            name='user',
        ),
        migrations.AddField(
            model_name='schedulednotifications',
            name='drivers_inventory_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='AcceptedRides',
        ),
        migrations.DeleteModel(
            name='BidRide',
        ),
        migrations.DeleteModel(
            name='CompletedBidOnRide',
        ),
        migrations.DeleteModel(
            name='CompletedRides',
        ),
        migrations.DeleteModel(
            name='DriverAnnounceArrival',
        ),
        migrations.DeleteModel(
            name='DriverReviews',
        ),
        migrations.DeleteModel(
            name='DriversPoints',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='RejectedRides',
        ),
        migrations.DeleteModel(
            name='RequestRide',
        ),
        migrations.DeleteModel(
            name='RideStarted',
        ),
        migrations.DeleteModel(
            name='SearchedDestinations',
        ),
        migrations.DeleteModel(
            name='Sos',
        ),
    ]
