# Generated by Django 4.0.3 on 2022-04-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0010_rename_lat_lng_driverslocation_position_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverslocation',
            old_name='position_lat',
            new_name='place_id',
        ),
        migrations.RemoveField(
            model_name='driverslocation',
            name='position_lng',
        ),
    ]
