# Generated by Django 4.0.3 on 2022-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0010_alter_scheduleride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='time_sent',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
