# Generated by Django 4.0.3 on 2022-11-01 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0011_addtopaymenttoday_phone_addtopaymenttoday_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesrequest',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_making_expense', to=settings.AUTH_USER_MODEL),
        ),
    ]
