# Generated by Django 4.0.3 on 2022-05-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0012_searcheddestinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='searcheddestinations',
            name='place_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
