# Generated by Django 4.0.3 on 2022-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0012_driverendtrip_ride_driverstarttrip_ride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Active', 'In Active'), ('Inspection', 'Inspection'), ('In the shop', 'In the shop'), ('Stolen', 'Stolen'), ('In Garage', 'In Garage')], default='In Active', max_length=255)),
                ('brand', models.CharField(choices=[('Audi', 'Audi'), ('Alfa Romeo', 'Alfa Romeo'), ('Acura', 'Acura'), ('Aston Martin', 'Aston Martin'), ('BMW', 'BMW'), ('Bentley', 'Bentley'), ('Chevrolet', 'Chevrolet'), ('Citroen', 'Citroen'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Daewoo', 'Daewoo'), ('Daewoo', 'Daewoo'), ('Eagle', 'Eagle'), ('Edsel', 'Edsel'), ('Englon', 'Englon'), ('Ford', 'Ford'), ('Fiat', 'Fiat'), ('Foton', 'Foton'), ('GMC', 'GMC'), ('Genesis', 'Genesis'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infinity', 'Infinity'), ('Isuzu', 'Isuzu'), ('Jeep', 'Jeep'), ('Jetta', 'Jetta'), ('Kia', 'Kia'), ('Kenworth', 'Kenworth'), ('Lexus', 'Lexus'), ('Land Rover', 'Land Rover'), ('Maserati', 'Maserati'), ('Mazda', 'Mazda'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Suzuki', 'Suzuki'), ('Saturn', 'Saturn'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], default='Toyota', max_length=255)),
                ('model', models.CharField(default='Yaris', max_length=100)),
                ('color', models.CharField(choices=[('Yellow', 'Yellow'), ('White', 'White'), ('Black', 'Black'), ('Gray', 'Gray'), ('Red', 'Red'), ('Dark Blue', 'Dark Blue'), ('Light Blue', 'Light Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Pink', 'Pink'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Beige', 'Beige')], default='White', max_length=255)),
                ('year', models.CharField(default='2000', max_length=5)),
                ('license_plate_number', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('body_number', models.CharField(max_length=50)),
                ('registration_certificate_number', models.CharField(max_length=50)),
                ('taxi_license_number', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Authomatic', 'Authomatic'), ('Robotized', 'Robotized'), ('Variator', 'Variator')], default='Automatic', max_length=30)),
                ('boosters', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=4)),
                ('child_safety_seats', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=4)),
                ('branded_wrap', models.BooleanField(default=False)),
                ('light_box', models.BooleanField(default=False)),
                ('fleet_car', models.CharField(choices=[('Unselected', 'Unselected'), ('Yes', 'Yes'), ('No', 'No')], default='Unselected', max_length=20)),
                ('code_name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Comfort', 'Comfort'), ('Courier', 'Courier'), ('Economy', 'Economy'), ('Delivery', 'Delivery')], default='Comfort', max_length=50)),
                ('picture', models.ImageField(upload_to='car_photos')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
