# Generated by Django 4.0.3 on 2022-08-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0012_asktoloadwallet_completedscheduledridestoday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleride',
            name='assigned_driver',
        ),
    ]
