# Generated by Django 4.0.3 on 2022-05-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0013_searcheddestinations_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='drop_off_place_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notifications',
            name='pick_up_place_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='requestride',
            name='drivers_location_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requestride',
            name='passengers_drop_off_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requestride',
            name='passengers_pick_up_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
