# Generated by Django 4.0.3 on 2022-09-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0013_registervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverswallet',
            name='default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=70.0, max_digits=10),
        ),
    ]
