# Generated by Django 4.0.3 on 2022-11-21 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0014_alter_driverrequestcommission_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('date_transferred', models.DateField(auto_now_add=True)),
                ('time_transferred', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
