# Generated by Django 4.0.3 on 2022-09-01 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0014_driverswallet_default_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerswallet',
            name='de_passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passengerloadingwallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
