# Generated by Django 4.0.3 on 2022-09-01 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0015_passengerswallet_de_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerswallet',
            name='de_passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengerloadingwallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
