# Generated by Django 4.0.3 on 2022-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0015_walletaddition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtopaymenttoday',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
