# Generated by Django 4.0.3 on 2022-08-12 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0015_alter_scheduleride_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='asktoloadwallet',
            name='time_requested',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asktoloadwallet',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
