# Generated by Django 4.0.3 on 2022-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0015_notifications_passengers_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='passengers_dropff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='passengers_pickup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
