# Generated by Django 4.0.3 on 2022-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0016_asktoloadwallet_time_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asktoloadwallet',
            name='title',
            field=models.CharField(default='Wants to load wallet', max_length=200),
        ),
    ]
