# Generated by Django 4.0.3 on 2022-09-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_alter_addtoverified_user'),
        ('taxinet_api', '0016_alter_passengerswallet_de_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerswallet',
            name='de_passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengerloadingwallet', to='taxinet_users.passengerprofile'),
        ),
    ]
