# Generated by Django 4.0.3 on 2022-09-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_alter_addtoverified_user'),
        ('taxinet_api', '0017_alter_passengerswallet_de_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverswallet',
            name='de_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverswallet', to='taxinet_users.driverprofile'),
        ),
        migrations.AlterField(
            model_name='driverasktoloadwallet',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_users.driverprofile'),
        ),
    ]
