# Generated by Django 4.0.3 on 2022-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0017_asktoloadwallet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='asktoloadwallet',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
        migrations.AddField(
            model_name='contactadmin',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
        migrations.AddField(
            model_name='contactus',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
        migrations.AddField(
            model_name='drivervehicleinventory',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
        migrations.AlterField(
            model_name='complains',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
    ]
