# Generated by Django 4.0.3 on 2022-05-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0017_notifications_ride_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidride',
            name='bid_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidride',
            name='bid_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidride',
            name='driver_accepted_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidride',
            name='driver_rejected_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidride',
            name='passenger_accepted_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidride',
            name='passenger_rejected_bid',
            field=models.BooleanField(default=False),
        ),
    ]
