# Generated by Django 4.0.3 on 2022-11-22 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0017_workextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallForInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_for_inspection', models.CharField(max_length=100)),
                ('date_informed', models.DateField(auto_now_add=True)),
                ('time_informed', models.TimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
