# Generated by Django 4.0.3 on 2022-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0018_bidride_bid_accepted_bidride_bid_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidride',
            name='driver_accepted_bid',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='driver_rejected_bid',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='passenger_accepted_bid',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='passenger_rejected_bid',
        ),
        migrations.AddField(
            model_name='bidride',
            name='bid_message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
