# Generated by Django 4.0.3 on 2022-11-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0018_callforinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='callforinspection',
            name='time_for_inspection',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='callforinspection',
            name='day_for_inspection',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=100),
        ),
    ]
