# Generated by Django 4.0.3 on 2022-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0018_driverswallet_de_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='vehicle_brand',
            field=models.CharField(choices=[('Avalon', 'Avalon'), ('BELTA', 'BELTA'), ('CAMRY', 'CAMRY'), ('CENTURY', 'CENTURY'), ('ALLION', 'ALLION'), ('LEVIN GT', 'LEVIN GT'), ('CROWN', 'CROWN'), ('ETIOS', 'ETIOS'), ('MIRAI', 'MIRAI'), ('PRIUS', 'PRIUS'), ('AGYA/WIGO', 'AGYA/WIGO'), ('AQUA', 'AQUA'), ('COROLLA', 'COROLLA'), ('GR COROLLA', 'GR COROLLA'), ('ETIOS', 'ETIOS'), ('GLANZA', 'GLANZA'), ('PASSO', 'PASSO'), ('YARIS', 'YARIS'), ('4RUNNER', '4RUNNER'), ('VENZA', 'VENZA'), ('HIGHLANDER', 'HIGHLANDER'), ('LAND CRUISER', 'LAND CRUISER'), ('RAV4', 'RAV4'), ('RUSH', 'RUSH'), ('Vitz', 'Vitz')], default='Vitz', max_length=255),
        ),
    ]
