# Generated by Django 4.0.3 on 2022-05-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0019_remove_bidride_driver_accepted_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidride',
            name='bid_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bidride',
            name='bid_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
