# Generated by Django 4.0.3 on 2022-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0019_callforinspection_time_for_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivervehicleinventory',
            name='inspector_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
