# Generated by Django 4.0.3 on 2022-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0019_alter_drivervehicleinventory_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registervehicle',
            name='body_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='code_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='fleet_car',
            field=models.CharField(blank=True, choices=[('Unselected', 'Unselected'), ('Yes', 'Yes'), ('No', 'No')], default='Unselected', max_length=20),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='license_plate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='picture',
            field=models.ImageField(blank=True, upload_to='car_photos'),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='registration_certificate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='taxi_license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
