# Generated by Django 4.0.3 on 2022-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0020_alter_bidride_bid_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidride',
            name='driver_accepted_bid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
