# Generated by Django 4.0.3 on 2022-11-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0020_drivervehicleinventory_inspector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='inspector_name',
            field=models.CharField(max_length=50),
        ),
    ]
