# Generated by Django 4.0.3 on 2022-09-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_alter_addtoverified_user'),
        ('taxinet_api', '0020_alter_registervehicle_body_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='break_fluid',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='driving_mirror',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='electric_windows',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='engine_noise',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='engine_oil',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='excessive_smoke',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='fire_extinguisher',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='first_aid_box',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='foot_break',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='fuel_level',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='hand_break',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='head_lights',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='horn',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='interior_lights',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='power_steering_fluid',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='radiator_engine_coolant',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='registration_plate',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='reverse_lights',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='seat_belts',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='side_mirror',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='steering_wheel',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='tail_rear_lights',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='tire_pressure',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='tire_thread_depth',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='trafficators',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='vehicle_brand',
            field=models.CharField(choices=[('Select a brand', 'Select a brand'), ('Avalon', 'Avalon'), ('BELTA', 'BELTA'), ('CAMRY', 'CAMRY'), ('CENTURY', 'CENTURY'), ('ALLION', 'ALLION'), ('LEVIN GT', 'LEVIN GT'), ('CROWN', 'CROWN'), ('ETIOS', 'ETIOS'), ('MIRAI', 'MIRAI'), ('PRIUS', 'PRIUS'), ('AGYA', 'AGYA'), ('AQUA', 'AQUA'), ('COROLLA', 'COROLLA'), ('ETIOS', 'ETIOS'), ('GLANZA', 'GLANZA'), ('PASSO', 'PASSO'), ('YARIS', 'YARIS'), ('4RUNNER', '4RUNNER'), ('VENZA', 'VENZA'), ('HIGHLANDER', 'HIGHLANDER'), ('LAND CRUISER', 'LAND CRUISER'), ('RAV4', 'RAV4'), ('RUSH', 'RUSH'), ('Vitz', 'Vitz')], default='Vitz', max_length=255),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='warning_triangle',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='wheel_bearing_noise',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='wheel_nuts',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='windscreen',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='windscreen_wipers',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='wiper_washer_fluid',
            field=models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30),
        ),
        migrations.AlterField(
            model_name='registervehicle',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Fiat', 'Fiat'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infinity', 'Infinity'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], default='Toyota', max_length=255),
        ),
        migrations.CreateModel(
            name='AddToPaymentToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('time_paid', models.TimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_users.driverprofile')),
            ],
        ),
    ]
