# Generated by Django 4.0.3 on 2022-08-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0020_alter_asktoloadwallet_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asktoloadwallet',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
