# Generated by Django 4.0.3 on 2022-09-03 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0021_alter_drivervehicleinventory_break_fluid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtopaymenttoday',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
