# Generated by Django 4.0.3 on 2022-05-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0021_bidride_driver_accepted_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidride',
            name='bid_accepted',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='bid_message',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='bid_rejected',
        ),
        migrations.RemoveField(
            model_name='bidride',
            name='driver_accepted_bid',
        ),
        migrations.CreateModel(
            name='AcceptRejectBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_accepted', models.BooleanField(blank=True, default=False)),
                ('bid_rejected', models.BooleanField(blank=True, default=False)),
                ('bid_message', models.CharField(blank=True, max_length=150, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.bidride')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ride_to_bid', to='taxinet_api.requestride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accepting_rejecting_bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
