# Generated by Django 4.0.3 on 2022-09-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0022_alter_addtopaymenttoday_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedScheduledRides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('scheduled_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride')),
            ],
        ),
        migrations.DeleteModel(
            name='CompletedScheduledRidesToday',
        ),
    ]
