# Generated by Django 4.0.3 on 2022-05-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0022_remove_bidride_bid_accepted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptRejectBid',
        ),
    ]
