# Generated by Django 4.0.3 on 2022-09-07 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0023_completedscheduledrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverendtrip',
            name='payment_method',
            field=models.CharField(default='Wallet', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='drop_off_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduleride',
            name='pickup_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='WorkAndPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('years', models.IntegerField(default=2)),
                ('start_date', models.CharField(blank=True, max_length=20)),
                ('end_date', models.CharField(blank=True, max_length=20)),
                ('fully_paid', models.BooleanField(default=False)),
                ('date_started', models.DateField(auto_now_add=True)),
                ('time_started', models.TimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('date_transferred', models.DateField(auto_now_add=True)),
                ('time_transferred', models.TimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receiving_wallet', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
