# Generated by Django 4.0.3 on 2022-12-01 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0023_alter_drivervehicleinventory_inspector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivervehicleinventory',
            name='vehicle_brand',
            field=models.CharField(choices=[('Select a brand', 'Select a brand'), ('Avalon', 'Avalon'), ('BELTA', 'BELTA'), ('CAMRY', 'CAMRY'), ('CENTURY', 'CENTURY'), ('ALLION', 'ALLION'), ('LEVIN GT', 'LEVIN GT'), ('CROWN', 'CROWN'), ('ETIOS', 'ETIOS'), ('MIRAI', 'MIRAI'), ('PRIUS', 'PRIUS'), ('AGYA', 'AGYA'), ('AQUA', 'AQUA'), ('COROLLA', 'COROLLA'), ('ETIOS', 'ETIOS'), ('GLANZA', 'GLANZA'), ('PASSO', 'PASSO'), ('YARIS', 'YARIS'), ('4RUNNER', '4RUNNER'), ('VENZA', 'VENZA'), ('HIGHLANDER', 'HIGHLANDER'), ('LAND CRUISER', 'LAND CRUISER'), ('RAV4', 'RAV4'), ('RUSH', 'RUSH'), ('Vitz', 'Vitz')], default='Vitz', max_length=255),
        ),
        migrations.CreateModel(
            name='UserRequestTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('top_up_option', models.CharField(default='Mobile Money', max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('time_requested', models.TimeField(auto_now_add=True)),
                ('accounts', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
                ('administrator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting_topup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
