# Generated by Django 4.0.3 on 2022-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0024_rejectedrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='drivers_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='drivers_lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestride',
            name='drivers_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestride',
            name='drivers_lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
