# Generated by Django 4.0.3 on 2022-09-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0024_driverendtrip_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverendtrip',
            name='payment_method',
            field=models.CharField(choices=[('Select payment method', 'Select payment method'), ('Wallet', 'Wallet'), ('Cash', 'Cash')], default='Wallet', max_length=30),
        ),
    ]
