# Generated by Django 4.0.3 on 2022-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0024_alter_drivervehicleinventory_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesttopup',
            name='top_up_option',
            field=models.CharField(choices=[('Select Payment Option', 'Select Payment Option'), ('Mobile Money', 'Mobile Money'), ('Bank', 'Bank')], default='Mobile Money', max_length=50),
        ),
    ]
