# Generated by Django 4.0.3 on 2022-12-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0025_alter_userrequesttopup_top_up_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequesttopup',
            name='top_up_option',
            field=models.CharField(choices=[('Select Payment Option', 'Select Payment Option'), ('Mobile Money', 'Mobile Money'), ('Ecobank', 'Ecobank')], default='Mobile Money', max_length=50),
        ),
    ]
