# Generated by Django 4.0.3 on 2022-05-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0025_notifications_drivers_lat_notifications_drivers_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestride',
            name='drivers_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestride',
            name='drivers_lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
