# Generated by Django 4.0.3 on 2022-09-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0026_alter_scheduleride_schedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtopaymenttoday',
            name='read',
            field=models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=10),
        ),
        migrations.AddField(
            model_name='addtopaymenttoday',
            name='title',
            field=models.CharField(default='Payment Today', max_length=255),
        ),
    ]
