# Generated by Django 4.0.3 on 2022-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0027_requestride_bid_completed_completedrides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='drivers_lat',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='drivers_lng',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='drivers_lat',
        ),
        migrations.RemoveField(
            model_name='requestride',
            name='drivers_lng',
        ),
        migrations.AddField(
            model_name='driverslocation',
            name='drivers_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverslocation',
            name='drivers_lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
