# Generated by Django 4.0.3 on 2023-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0027_remove_drivervehicleinventory_registration_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workandpay',
            old_name='years',
            new_name='number_of_years',
        ),
        migrations.RemoveField(
            model_name='workandpay',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='workandpay',
            name='amount_to_pay',
        ),
        migrations.AddField(
            model_name='workandpay',
            name='daily_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='interest_on_car',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='principle_amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='total_amount_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='total_value_of_car',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='upfront_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='workandpay',
            name='weekly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
