# Generated by Django 4.0.3 on 2022-09-16 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0028_wallets_updatedwallets_loadwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverendtrip',
            name='time_elapsed',
            field=models.CharField(default='00:00:00', max_length=225),
        ),
        migrations.CreateModel(
            name='RideMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('time_sent', models.TimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxinet_api.scheduleride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sending_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
