# Generated by Django 4.0.3 on 2022-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0028_remove_notifications_drivers_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestride',
            name='passenger_boarded',
            field=models.BooleanField(default=False),
        ),
    ]
