# Generated by Django 4.0.3 on 2022-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0029_requestride_passenger_boarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverslocation',
            name='location_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
