# Generated by Django 4.0.3 on 2022-09-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxinet_api', '0031_alter_ridemessages_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridemessages',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_sending_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ridemessages',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_sending_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
