# Generated by Django 4.0.3 on 2022-06-15 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0032_remove_notifications_ride_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestride',
            name='time_requested',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestride',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
