# Generated by Django 4.0.3 on 2022-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0033_requestride_time_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='passenger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
