# Generated by Django 4.0.3 on 2022-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0034_notifications_driver_notifications_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestride',
            name='drivers_location_place_id',
        ),
        migrations.AddField(
            model_name='completedbidonride',
            name='drivers_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='completedbidonride',
            name='drivers_lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='drivers_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='drivers_lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
