# Generated by Django 4.0.3 on 2022-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0035_remove_requestride_drivers_location_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestride',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestride',
            name='time_requested',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
