# Generated by Django 4.0.3 on 2022-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0036_alter_requestride_date_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedrides',
            name='passengers_lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='acceptedrides',
            name='passengers_lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
