# Generated by Django 4.0.3 on 2022-06-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0037_acceptedrides_passengers_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedbidonride',
            name='passengers_pickup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='completedbidonride',
            name='pick_up_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
