# Generated by Django 4.0.3 on 2022-06-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0038_completedbidonride_passengers_pickup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='passenger',
        ),
    ]
