# Generated by Django 4.0.3 on 2023-11-18 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(default='', max_length=255)),
                ('unique_number', models.CharField(default='', max_length=30)),
                ('vehicle_brand', models.CharField(choices=[('Select a brand', 'Select a brand'), ('Avalon', 'Avalon'), ('BELTA', 'BELTA'), ('CAMRY', 'CAMRY'), ('CENTURY', 'CENTURY'), ('ALLION', 'ALLION'), ('LEVIN GT', 'LEVIN GT'), ('CROWN', 'CROWN'), ('ETIOS', 'ETIOS'), ('MIRAI', 'MIRAI'), ('PRIUS', 'PRIUS'), ('AGYA', 'AGYA'), ('AQUA', 'AQUA'), ('COROLLA', 'COROLLA'), ('ETIOS', 'ETIOS'), ('GLANZA', 'GLANZA'), ('PASSO', 'PASSO'), ('YARIS', 'YARIS'), ('4RUNNER', '4RUNNER'), ('VENZA', 'VENZA'), ('HIGHLANDER', 'HIGHLANDER'), ('LAND CRUISER', 'LAND CRUISER'), ('RAV4', 'RAV4'), ('RUSH', 'RUSH'), ('Vitz', 'Vitz')], default='Vitz', max_length=255)),
                ('millage', models.CharField(default='', max_length=255)),
                ('windscreen', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('side_mirror', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('registration_plate', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('tire_pressure', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('driving_mirror', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('tire_thread_depth', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('wheel_nuts', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('engine_oil', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('fuel_level', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('break_fluid', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('radiator_engine_coolant', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('power_steering_fluid', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('wiper_washer_fluid', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('seat_belts', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('steering_wheel', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('horn', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('electric_windows', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('windscreen_wipers', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('head_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('trafficators', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('tail_rear_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('reverse_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('interior_lights', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('engine_noise', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('excessive_smoke', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('foot_break', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('hand_break', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('wheel_bearing_noise', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('warning_triangle', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('fire_extinguisher', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('first_aid_box', models.CharField(choices=[('Select Option', 'Select Option'), ('okay', 'okay'), ('no', 'no')], default='No', max_length=30)),
                ('checked_today', models.BooleanField(default=False)),
                ('date_checked', models.DateField(auto_now_add=True)),
                ('time_checked', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
