# Generated by Django 4.0.3 on 2023-11-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivervehicleinventory',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='drivervehicleinventory',
            name='unique_number',
        ),
        migrations.RemoveField(
            model_name='drivervehicleinventory',
            name='vehicle_brand',
        ),
    ]
