# Generated by Django 4.0.3 on 2023-09-14 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_api', '0003_registercarforrent_rentacar_vehicleinventory_and_more'),
        ('taxinet_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default_user.png', upload_to='profile_pics')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='addcardsuploaded',
            name='user',
        ),
        migrations.RemoveField(
            model_name='addtoverified',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administratorsprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bigtrucksadminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='investorsprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='promoterprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rideadminprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='promoter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unique_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Administrator', 'Administrator')], default='Passenger', max_length=50),
        ),
        migrations.DeleteModel(
            name='AccountsProfile',
        ),
        migrations.DeleteModel(
            name='AddCardsUploaded',
        ),
        migrations.DeleteModel(
            name='AddToVerified',
        ),
        migrations.DeleteModel(
            name='AdministratorsProfile',
        ),
        migrations.DeleteModel(
            name='BigTrucksAdminProfile',
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
        migrations.DeleteModel(
            name='InvestorsProfile',
        ),
        migrations.DeleteModel(
            name='PassengerProfile',
        ),
        migrations.DeleteModel(
            name='PromoterProfile',
        ),
        migrations.DeleteModel(
            name='RideAdminProfile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
