# Generated by Django 4.0.3 on 2022-06-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='ghana_card',
            new_name='back_side_ghana_card',
        ),
        migrations.RenameField(
            model_name='passengerprofile',
            old_name='ghana_card',
            new_name='back_side_ghana_card',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='front_side_ghana_card',
            field=models.ImageField(blank=True, upload_to='ghana_cards'),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='front_side_ghana_card',
            field=models.ImageField(blank=True, upload_to='ghana_cards'),
        ),
    ]
