# Generated by Django 4.0.3 on 2022-04-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_expiration_date',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
