# Generated by Django 4.0.3 on 2022-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_alter_driverprofile_license_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='next_of_kin_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
