# Generated by Django 4.0.3 on 2022-08-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_addtoverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtoverified',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_profile', to='taxinet_users.passengerprofile'),
        ),
        migrations.CreateModel(
            name='AddCardsUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_cards_profile', to='taxinet_users.passengerprofile')),
            ],
        ),
    ]
