# Generated by Django 4.0.3 on 2022-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_tracker_sim',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
