# Generated by Django 4.0.3 on 2022-06-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerprofile',
            name='ghana_card_number',
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='referral_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
