# Generated by Django 4.0.3 on 2022-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0002_alter_addtoverified_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='unique_code',
            field=models.IntegerField(default=2),
        ),
    ]
