# Generated by Django 4.0.3 on 2022-09-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_driverprofile_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='unique_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='unique_code',
            field=models.IntegerField(default=0),
        ),
    ]
