# Generated by Django 4.0.3 on 2022-07-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_remove_passengerprofile_ghana_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Driver', 'Driver'), ('Investor', 'Investor'), ('Administrator', 'Administrator')], default='Passenger', max_length=50),
        ),
    ]
