# Generated by Django 4.0.3 on 2022-05-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_alter_driverprofile_next_of_kin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='taxinet_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
