# Generated by Django 4.0.3 on 2022-11-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_user_driver_tracker_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
