# Generated by Django 4.0.3 on 2022-10-31 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0003_driverprofile_phone_driverprofile_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='promoter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_registering_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
