# Generated by Django 4.0.3 on 2022-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0004_user_user_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promoter',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
