# Generated by Django 4.0.3 on 2022-09-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0004_passengerprofile_unique_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='unique_code',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='unique_code',
            field=models.CharField(default='', max_length=500),
        ),
    ]
