# Generated by Django 4.0.3 on 2022-11-02 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0004_passengerprofile_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promoter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_registering_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
