# Generated by Django 4.0.3 on 2022-11-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0005_alter_user_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsprofile',
            name='unique_code',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='promoterprofile',
            name='unique_code',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='rideadminprofile',
            name='unique_code',
            field=models.CharField(default='', max_length=500),
        ),
    ]
