# Generated by Django 4.0.3 on 2022-11-02 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0005_user_promoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerprofile',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_registering_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='promoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_registering_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
