# Generated by Django 4.0.3 on 2022-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxinet_users', '0008_alter_passengerprofile_promoter_alter_user_promoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerprofile',
            name='promoter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='promoter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
