# Generated by Django 4.0.3 on 2023-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPayAndDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('pick_up_date', models.CharField(max_length=10)),
                ('payment_period', models.CharField(choices=[('1 Yr', '1 Yr'), ('2 Yrs', '2 Yrs'), ('3 Yrs', '3 Yrs')], default='1 Yr', max_length=10)),
                ('period_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('request_approved', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
