# Generated by Django 4.0.3 on 2024-04-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_drive', '0008_alter_requestpayanddrive_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtoapprovedpayanddrive',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
