# Generated by Django 4.0.3 on 2024-05-27 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay_drive', '0015_requestpayanddrive_time_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpayanddrive',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestpayanddrive',
            name='time_requested',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
