# Generated by Django 4.0.3 on 2024-04-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=10)),
                ('seater', models.IntegerField(default=5)),
                ('daily_payment', models.CharField(max_length=500)),
                ('above_a_week', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='Cars_for_rent')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_detail_pictures')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_for_rent.carsforrent')),
            ],
        ),
    ]
