# Generated by Django 4.0.3 on 2024-04-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_for_rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforrent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
