# Generated by Django 4.0.3 on 2024-04-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_for_rent', '0002_carsforrent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsforrent',
            name='above_a_week',
        ),
        migrations.RemoveField(
            model_name='carsforrent',
            name='daily_payment',
        ),
    ]
