# Generated by Django 4.0.3 on 2024-05-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_for_rent', '0003_remove_carsforrent_above_a_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforrent',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
