# Generated by Django 4.0.3 on 2024-05-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_for_rent', '0005_carsforrent_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforrent',
            name='color',
            field=models.CharField(default='Black', max_length=100),
        ),
    ]
