# Generated by Django 4.0.3 on 2024-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_for_rent', '0007_carsforrent_drive_type_carsforrent_k200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsforrent',
            name='just_ksi',
            field=models.BooleanField(default=False),
        ),
    ]
