# Generated by Django 4.0.3 on 2024-03-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='kitchen_images')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
