# Generated by Django 4.0.3 on 2023-11-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_truck', models.CharField(max_length=30)),
                ('items_delivering', models.CharField(max_length=100)),
                ('pick_up_date', models.CharField(max_length=10)),
                ('delivery_date', models.CharField(max_length=10)),
                ('request_approved', models.BooleanField(default=False)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
