# Generated by Django 4.0.3 on 2023-11-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestdelivery',
            name='items_delivering',
        ),
        migrations.AlterField(
            model_name='requestdelivery',
            name='delivery_truck',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Motor Bike', 'Motor Bike'), ('Aboboyaa', 'Aboboyaa')], default='Truck', max_length=30),
        ),
    ]
